[build]
command = "yarn nx export blog"
publish = "./dist/apps/blog/exported/"


[[plugins]]
package = "netlify-plugin-cache-nextjs"

[plugins.inputs]
build_dir_path = "./dist/apps/blog/"

[[headers]]
for = "/*"

[headers.values]
Content-Security-Policy = """
default-src 'self' 'unsafe-inline' images.ctfassets.net fonts.googleapis.com fonts.gstatic.com;
style-src 'self' 'unsafe-inline' fonts.googleapis.com;
connect-src 'self'
"""


